# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: iridakos
email: ""
description: Personal blog of Lazarus Lazaridis with programming tutorials, tips and open source related posts.
baseurl: "" # the subpath of your site, e.g. /blog
production_url: "http://iridakos.com"
url: "http://iridakos.com" # the base hostname & protocol for your site
twitter_username: lazaru_s
github_username:  iridakos
linkedin_username: lazaruslazaridis
paginate: 10
paginate_path: "/posts/page-:num"
author: Lazarus Lazaridis
twitter:
  username: lazaru_s
logo: /assets/images/irida-favicon.png
links:
  https://twitter.com/lazaru_s
  https://www.linkedin.com/in/lazaruslazaridis
  https://github.com/iridakos

# Build settings
markdown: kramdown

include: ['_pages']

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
